spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CST
    username: root
    password: 123..123
  jap:
    hibernate:
#   自动创建更新，验证数据库表结构
      ddl-auto: update
#   设置数据库引擎为innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#   打印sql语句
    show-sql: true
